apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappproject-deployment
  labels:
    app: todoappproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoappproject
  template:
    metadata:
      labels:
        app: todoappproject
    spec:
      containers:
      - name: todoappproject-container
        image: achrafbrini007/todoappproject:latest  # Matches Jenkins pipeline
        ports:
        - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: todoappproject-service
spec:
  type: NodePort
  selector:
    app: todoappproject
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4173
    nodePort: 30080
